from flask import Flask, render_template, request, jsonify
import services
import database
import os

import logging

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

app = Flask(__name__)

# Ensure DB is initialized
database.init_db()

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/dashboard')
def dashboard():
    return render_template('dashboard.html')

@app.route('/api/process_voice', methods=['POST'])
def process_voice():
    try:
        data = request.json
        raw_text = data.get('text', '')
        hf_token = data.get('hf_token', '')
        
        if not raw_text:
            return jsonify({"error": "No text provided"}), 400
            
        logging.info(f"Processing text of length {len(raw_text)}")
        
        # 0. Get Explicit Language from Frontend
        source_lang_code = data.get('source_lang_code', 'auto')
        logging.info(f"Source Language Provided: {source_lang_code}")

        # 1. Detect Language (Fallback or confirmation)
        lang = services.detect_language(raw_text)
        logging.info(f"Detected language (Algo): {lang}")
        
        # 2. Translate to English (Using Explicit Source if available)
        # We pass source_lang_code to the translator to avoid guessing errors
        translated_text = services.translate_text(raw_text, target_lang='en', source_lang=source_lang_code)
        logging.info(f"Translated text: {translated_text[:50]}...")
        
        # 3. Generate MoM (Summary, Key Points, Actions)
        # Pass hf_token if user provided it
        mom_data = services.generate_mom(translated_text, hf_token=hf_token)
        logging.info("MoM generated successfully")
        
        # 4. Extract Structured Tasks
        # Use whatever tasks generated by MoM + extra extraction logic
        tasks = services.extract_tasks_logic(translated_text, mom_data.get('action_items', []))
        logging.info(f"Extracted {len(tasks)} tasks")
        
        # 5. Save to DB
        meeting_id = database.add_meeting(
            raw_text, 
            translated_text, 
            lang, 
            mom_data.get('summary', ''),
            mom_data.get('key_points', []),
            mom_data.get('decisions', [])
        )
        
        for task in tasks:
            database.add_task(
                task['title'],
                task['assignee'],
                task['deadline'],
                task['priority'],
                task['estimated_time'],
                task['risk_level'],
                meeting_id
            )
            
        return jsonify({
            "status": "success",
            "original": raw_text,
            "language": lang,
            "translated": translated_text,
            "mom": mom_data,
            "tasks": tasks
        })

    except Exception as e:
        logging.error(f"Error in process_voice: {e}", exc_info=True)
        return jsonify({"error": str(e)}), 500

@app.route('/api/tasks', methods=['GET'])
def get_tasks():
    tasks = database.get_all_tasks()
    return jsonify(tasks)

@app.route('/api/tasks/<int:task_id>', methods=['DELETE'])
def delete_task(task_id):
    database.delete_task(task_id)
    return jsonify({"status": "success"})

@app.route('/api/meeting/latest', methods=['GET'])
def get_latest_meeting():
    meeting = database.get_latest_meeting()
    if meeting:
        return jsonify(meeting)
    return jsonify({"error": "No meetings found"}), 404

if __name__ == '__main__':
    app.run(debug=False, host='0.0.0.0', port=5000)
